server:
  port: 8081

eureka:
  client:
    serviceUrl:
      defaultZone: ${EUREKA_URI:http://localhost:8761/eureka}
  instance:
    preferIpAddress: true


spring:
  cloud:
    gateway:
      routes:
        - id: smart-time-sheet
          uri: lb://smart-time-sheet
          predicates:
            - Path=/summary/**
        - id: auth
          uri: lb://auth
          predicates:
            - Path=/auth/**
        - id: profile
          uri: lb://profile
          predicates:
            - Path=/profile/**



