spring:
  data:
    mongodb:
      database: smart-time-sheet
  application:
    name: smart-time-sheet

server:
  port: 8081
eureka:
  client:
    serviceUrl:
      defaultZone: ${EUREKA_URI:http://localhost:8761/eureka}
  instance:
    preferIpAddress: true




